### ISSUE TITLE
Compilation errors with MSVC

### ISSUE THREAD

**Issue by mspeder** [adamharrison/liquid-cpp#2]
Hello Adam,

MSVC compiler is reporting multiple errors which prevent successful compilation :
- in lexer.h, line 42 return type should be **std::string** instead of simply string (return statement in line #53 is ok)
- dialect.cpp, should **#include "functional"** header because code is using std:divides which is officially defined there (see https://en.cppreference.com/w/cpp/utility/functional/divides)
- in interface.cpp, lines 32 to 55, use of **designated initializers requires C++20** (https://en.cppreference.com/w/cpp/language/aggregate_initialization)

The last one is a bit harder to fix, as it requires either move to C++20 in cmake or refactoring the code to avoid designated initializers.
gcc/clang seem less strict on designated initializers in C++17 but this is not conform to C++ official standard, so it is not safe to rely on it.

Thanks a lot !

Matthieu

**Comment by adamharrison** [comment]
Hi!

> in lexer.h, line 42 return type should be std::string instead of simply string (return statement in line #53 is ok)
> dialect.cpp, should #include "functional" header because code is using std:divides which is officially defined there (see https://en.cppreference.com/w/cpp/utility/functional/divides)

Good catch, I'll fix.

> in interface.cpp, lines 32 to 55, use of designated initializers requires C++20 (https://en.cppreference.com/w/cpp/language/aggregate_initialization)

I'll modify this to be C++17 compatible.

Thanks for bringing to my attention.

**Comment by adamharrison** [comment]
OK, this should be fixed in `master`; can you confirm @mspeder ?

**Comment by mspeder** [comment]
Hi @adamharrison 

Yes, I confirm compilation is now successful. Thanks a lot for your support !
I found another small issue when compiled with Debug mode. The cmake file adds /Wextra in that case, which is not a valid flag on MSVC and this breaks compilation.
However this is not really a problem for me, since Release mode is working perfect anyway.

Thanks again,

Matthieu

**Comment by adamharrison** [comment]
OK, perfect, I'll remove that; I don't really use it for devlopment anyway.
